# See https://pycqa.github.io/isort/docs/configuration/github_action.html
name: isort

on:
  - pull_request

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: psf/black@stable
