# See https://pycqa.github.io/isort/docs/configuration/github_action.html
name: isort

on:
  - pull_request

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: jamescurtin/isort-action@master
